removed compiled libs and updated cmake (linux support)

diff --git a/.github/workflows/build-macos-arm64.yml b/.github/workflows/build-macos-arm64.yml
--- a/.github/workflows/build-macos-arm64.yml
+++ b/.github/workflows/build-macos-arm64.yml
@@ -13,9 +13,23 @@ jobs:
     - name: Checkout repository
       uses: actions/checkout@v2
 
+    - name: Install Homebrew
+      run: |
+        if ! command -v brew &> /dev/null; then
+          echo "Homebrew not found, installing..."
+          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
+        else
+          echo "Homebrew is already installed."
+        fi
+
+    - name: Install Dependencies
+      run: |
+        brew update
+        brew install cmake glfw assimp freetype
+
     - name: Set up CMake
       run: |
-        mkdir build
+        mkdir -p build
         cd build
         cmake ..
 
